## Women Cloth Reviews Prediction with Multinomial Naive Bayes

### Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('WomenClothReviews.csv')

In [12]:
df = df.drop(['Unnamed: 0'], axis=1)

In [13]:
df

Clothing ID  Age                                              Title  \
0              767   33                                                NaN   
1             1080   34                                                NaN   
2             1077   60                            Some major design flaws   
3             1049   50                                   My favorite buy!   
4              847   47                                   Flattering shirt   
...            ...  ...                                                ...   
23481         1104   34                     Great dress for many occasions   
23482          862   48                         Wish it was made of cotton   
23483         1104   31                              Cute, but see through   
23484         1084   28  Very cute dress, perfect for summer parties an...   
23485         1104   52                    Please make more like this one!   

                                             Review Text  Rating  \
0      Absolutely wonderful - silky and sexy and comf...       4   
1      Love this dress!  it's sooo pretty.  i happene...       5   
2      I had such high hopes for this dress and reall...       3   
3      I love, love, love this jumpsuit. it's fun, fl...       5   
4      This shirt is very flattering to all due to th...       5   
...                                                  ...     ...   
23481  I was very happy to snag this dress at such a ...       5   
23482  It reminds me of maternity clothes. soft, stre...       3   
23483  This fit well, but the top was very see throug...       3   
23484  I bought this dress for a wedding i have this ...       3   
23485  This dress in a lovely platinum is feminine an...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
0                    1                        0       Initmates   
1                    1                        4         General   
2                    0                        0         General   
3                    1                        0  General Petite   
4                    1                        6         General   
...                ...                      ...             ...   
23481                1                        0  General Petite   
23482                1                        0  General Petite   
23483                0                        1  General Petite   
23484                1                        2         General   
23485                1                       22  General Petite   

      Department Name Class Name  
0            Intimate  Intimates  
1             Dresses    Dresses  
2             Dresses    Dresses  
3             Bottoms      Pants  
4                Tops    Blouses  
...               ...        ...  
23481         Dresses    Dresses  
23482            Tops      Knits  
23483         Dresses    Dresses  
23484         Dresses    Dresses  
23485         Dresses    Dresses  

[23486 rows x 10 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [15]:
df.shape

(23486, 10)

### Missing Value

In [16]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [18]:
df[df['Review Text']==""]=np.NaN

In [20]:
df['Review Text'].fillna('No Review', inplace=True)

In [21]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [22]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

### Defining Y and X

In [23]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [25]:
x = df['Review Text']

In [26]:
y = df['Rating']

In [27]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

### Train Test Split

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, stratify=y, random_state=82529)

In [30]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

### Getting Features Text Conversion to Tokens

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features = 5000)

In [34]:
x_train = cv.fit_transform(x_train)

In [35]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 bought', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [36]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
x_test = cv.fit_transform(x_test)

In [38]:
cv.get_feature_names_out()

array(['00 petite', '10 10', '10 12', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [39]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Model Train

In [40]:
from sklearn.naive_bayes import MultinomialNB

In [41]:
model = MultinomialNB()

In [42]:
model.fit(x_train, y_train)

MultinomialNB()

### Model Prediction

In [43]:
y_pred = model.predict(x_test)

In [44]:
y_pred.shape

(7046,)

In [45]:
y_pred

array([5., 4., 4., ..., 5., 5., 4.])

### Probability of Each Predicted Class

In [46]:
model.predict_proba(x_test)

array([[0.01656485, 0.00366442, 0.00244854, 0.01099159, 0.9663306 ],
       [0.37836996, 0.03520083, 0.1733739 , 0.40039855, 0.01265676],
       [0.00444072, 0.02805627, 0.20875437, 0.63552743, 0.12322121],
       ...,
       [0.02567297, 0.09400242, 0.03595057, 0.03813866, 0.80623538],
       [0.04163943, 0.05082139, 0.23323542, 0.12371549, 0.55058827],
       [0.01464732, 0.3679002 , 0.17178145, 0.42732863, 0.01834241]])

### Model Evaluation

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
confusion_matrix(y_test, y_pred)

array([[  29,   21,   27,   49,  127],
       [  54,   48,   66,   99,  203],
       [  87,   61,  112,  176,  425],
       [ 141,  113,  165,  335,  769],
       [ 335,  254,  351,  687, 2312]], dtype=int64)

In [54]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.04      0.11      0.06       253
         2.0       0.10      0.10      0.10       470
         3.0       0.16      0.13      0.14       861
         4.0       0.25      0.22      0.23      1523
         5.0       0.60      0.59      0.59      3939

    accuracy                           0.40      7046
   macro avg       0.23      0.23      0.23      7046
weighted avg       0.42      0.40      0.41      7046



### Recategories Ratings as Poor (0) and Good (1)

In [55]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [57]:
# re-rating as 1,2,3 as 0 and 4,5 as 1

df.replace({'Rating' : {1:0, 2:0, 3:0, 4:1, 5:1}}, inplace=True)

In [58]:
y = df['Rating']

In [60]:
x = df['Review Text']

### Train Test Split

In [61]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, stratify=y, random_state=82529)

In [62]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

### Getting Feature Text Conversion to Tokens

In [63]:
cv = CountVectorizer(lowercase = True, analyzer = 'word', ngram_range=(2,3), stop_words = 'english', max_features = 5000)

In [64]:
x_train = cv.fit_transform(x_train)
x_test = cv.fit_transform(x_test)

### Getting Model Retrain

In [65]:
model = MultinomialNB()

In [66]:
model.fit(x_train, y_train)

MultinomialNB()

### Model Prediction

In [67]:
y_pred = model.predict(x_test)

In [68]:
y_pred.shape

(7046,)

In [70]:
y_pred

array([1., 1., 0., ..., 0., 1., 1.])

### Model Evaluation

In [71]:
confusion_matrix(y_test, y_pred)

array([[ 474, 1109],
       [ 883, 4580]], dtype=int64)

In [72]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.35      0.30      0.32      1583
         1.0       0.81      0.84      0.82      5463

    accuracy                           0.72      7046
   macro avg       0.58      0.57      0.57      7046
weighted avg       0.70      0.72      0.71      7046

